### ISSUE TITLE
Edit and list spaces as described in Figma sketch, and first datasets imported

### ISSUE THREAD

**Issue by DanielJackson-Oslo** [lnu-norge/lokaler.lnu.no#5]
## Rationale

Get the project started with some basic data models and views, based on the user researched Figma sketch:
https://www.figma.com/proto/SLtkuwmMcUpYOArLWCEYvV/Lokaler---Designskisser?node-id=136%3A9621&starting-point-node-id=136%3A9621 

## Appetite 

A week. Then we can re-asses where we are.

## Details

To get the project started, we need minimum: 

- [x] Datamodels for Spaces and related models (reviews, facilities, facility reviews) @mathias234 
- [x] Some view listing those spaces and viewing them @DanielJackson-Oslo 
- [ ] A dataset to import spaces from Nasjonalt Skoleregister @DanielJackson-Oslo 

If we have time, we could go further to:
- [x] Showing spaces on a map
- [x] Editing spaces
- [x] Adding spaces (outside of Rails console / primitives)
- [ ] Primitive filtering of spaces

But those are probably for a future pitch!

**Comment by asolvang** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Edit and list spaces as described in Figma sketch, and first datasets imported](https://trello.com/c/mMpetu4k/42-edit-and-list-spaces-as-described-in-figma-sketch-and-first-datasets-imported)
