### ISSUE TITLE
Import dataset from NSR, to get data to play with

### ISSUE THREAD

**Issue by DanielJackson-Oslo** [lnu-norge/lokaler.lnu.no#6]
As we have done in experiments, we should import schools from NSR to get some real data to play with. 

## Blocked 

Needs a proper datamodel for spaces before import.

**Comment by asolvang** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Import data from NSR](https://trello.com/c/dlElNhsT/43-import-data-from-nsr)
